[versions]
detekt = "1.17.0"
kotest = { require = "4.6.0" }
publish-on-central = "0.5.0"

[libraries]
mockito = { group = "org.mockito", name = "mockito-core", version = "3.10.0" }
japicmp = { module = "com.github.siom79.japicmp:japicmp", version.require = "0.15.+" }

